// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmryXRpBKEugGEqUeLYv6nQ5RSTQSEzow',
    appId: '1:164132013513:web:b76f781d82962b4db75418',
    messagingSenderId: '164132013513',
    projectId: 'sbgprofesores-70c64',
    authDomain: 'sbgprofesores-70c64.firebaseapp.com',
    storageBucket: 'sbgprofesores-70c64.firebasestorage.app',
    measurementId: 'G-CNDTNV1GPJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZEO0kE3_33a3E_TRRtvVlOogA-M9KSFU',
    appId: '1:164132013513:android:1bb2d16c4f8860f9b75418',
    messagingSenderId: '164132013513',
    projectId: 'sbgprofesores-70c64',
    storageBucket: 'sbgprofesores-70c64.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1zZ8rhw5_rWr3QddxwGKg6caKczBPlLQ',
    appId: '1:164132013513:ios:8896dd6cfbd46c46b75418',
    messagingSenderId: '164132013513',
    projectId: 'sbgprofesores-70c64',
    storageBucket: 'sbgprofesores-70c64.firebasestorage.app',
    iosBundleId: 'com.example.sbgProfesores',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1zZ8rhw5_rWr3QddxwGKg6caKczBPlLQ',
    appId: '1:164132013513:ios:8896dd6cfbd46c46b75418',
    messagingSenderId: '164132013513',
    projectId: 'sbgprofesores-70c64',
    storageBucket: 'sbgprofesores-70c64.firebasestorage.app',
    iosBundleId: 'com.example.sbgProfesores',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmryXRpBKEugGEqUeLYv6nQ5RSTQSEzow',
    appId: '1:164132013513:web:67080f2c15ff7867b75418',
    messagingSenderId: '164132013513',
    projectId: 'sbgprofesores-70c64',
    authDomain: 'sbgprofesores-70c64.firebaseapp.com',
    storageBucket: 'sbgprofesores-70c64.firebasestorage.app',
    measurementId: 'G-78S80QX8LB',
  );
}
